### PR TITLE
WIP: New tablature source e chords

### PR DESCRIPTION
**Pull request by giancarloGiuffra**
#8 
The new source for tabs is [e-chords](https://www.e-chords.com/tabs). The scraper extracts tabs of the form:
* E| ... e.g. [titanic](https://www.e-chords.com/tabs/titanic/rose-and-jack)
* e| ... e.g. [ave maria](https://www.e-chords.com/tabs/franz-peter-schubert/ave-maria)
* e: ... e.g [hotel california](https://www.e-chords.com/tabs/eagles/hotel-california)

I haven't yet touched the code in `tablature.js`. As is, the transformation to notes seems to be working well only for **ave maria** above. In the case of **titanic** there are less notes than expected and there are some undefined at the end, probably because in these tabs there are some pipes in the middle and not only at the end. In the case of **hotel california** there are a lot of undefined, maybe because these tabs use some symbols that are not recognized in the transformation.

Do you have any tips on how to proceed with the modification of `tablature.js`? Thanks

### CODE REVIEW

**Comment by ThiagoAugustoSM** [comment]
Hello @giancarloGiuffra , there are probably some mistakes on the [tablature.js](https://github.com/ThiagoAugustoSM/arduino-tablature/blob/master/src/tablature.js) due to some different characters non traced, as _x_, _b_ and others, since there is a type of structure to a tablature but nothing worldly defined.

The idea is to trackdown others pauses and it to the list of pauses on the script.

And as you may know on the Arduino only [one buzzer](https://www.arduino.cc/reference/en/language/functions/advanced-io/tone/) is able to be active by the tone function.

`Only one tone can be generated at a time. If a tone is already playing on a different pin, the call to tone() will have no effect. If the tone is playing on the same pin, the call will set its frequency.`

So some notes need to be refactored, as when you play a C3 and D3 at the same time. You need to make a composition of it, or choose only one.

I'm going to take a look at the the tablature and its undefineds and errors.

**Comment by giancarloGiuffra** [comment]
hi @ThiagoAugustoSM, thanks for the reply and sorry for the delay. I will check the `tablature.js` code better keeping in mind what you mentioned. I'll start by writing some tests based on the song [andei so](https://www.cifraclub.com.br/natiruts/andei-so/) from the `README.md`. Once I get the current behavior tested I'll tackle the tabs features not supported but present in the other songs above.

**Comment by ThiagoAugustoSM** [comment]
@giancarloGiuffra do you think it's better for us to review this commits that you have already done and merge it. And you could do a PR focusing on the other problems of the tablature? Since a new feature was added in this WIP.

**Comment by giancarloGiuffra** [comment]
@ThiagoAugustoSM I totally agree, it's better to review these commits and eventually merge them. I'll work on another PR for the tablature interpretation. Thanks.

**Review by ThiagoAugustoSM — APPROVED** [review]
Well noted. Do you think it would be good to add some syntax padronization?

**Review by ThiagoAugustoSM — CHANGES_REQUESTED** [review]
Since a scraper.js was created, so it doesn't need cheerio importing anymore in the index.js file, right? Only for consistency. I edited that on the latest commit.

**Review by ThiagoAugustoSM — APPROVED** [review]
That really makes more sense.

**Review by ThiagoAugustoSM — APPROVED** [review]

**Review by ThiagoAugustoSM — APPROVED** [review]

**Comment by ThiagoAugustoSM** [comment]
Thank you very much for the contribuition @giancarloGiuffra . Hope to see more of you here in this repo. :+1: :100:

**Comment by giancarloGiuffra** [comment]
Thanks @ThiagoAugustoSM , sorry for the late response. I'll try to get the other PR done as soon as possible. On the other hand, I tried to search the term on internet but I couldn't find anything, what is syntax padronization?

**Comment by ThiagoAugustoSM** [comment]
Maybe this expression doesn't exist hahaha, but i was telling about importing a package on the script that we weren't using.

**Pull request merged**
